apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-m
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/datam"  # 会自动在对应的节点上创建文件夹，用于存储数据，