apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 type: NodePort         # 配置为NodePort，外部可以访问
 ports:
 - port: 30080          # 容器间，服务调用的端口
   nodePort: 30080      # 外部访问的端口
   targetPort: 80       # 容器暴露的端口，与Dockerfile暴露端口保持一致
   protocol: TCP
   name: http
 selector:
  app: mynginx