apiVersion: v1
kind: Pod
metadata: 
  name: producer-consumer
spec:
  nodeName: node01
  containers:
    - name: producer
      image: 192.168.111.10:5000/busybox:latest
      volumeMounts: 
      - name: shared-volume
        mountPath: /producer_dir
      args:
      - /bin/sh
      - -c
      - echo "hello this is producer on node02" > /producer_dir/hello ; sleep 3600
  volumes:
  - name: shared-volume
    emptyDir: {}